version: '3.8'

services:
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"  # Different port to avoid conflicts with dev/prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      DB_HOST: test-db
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: test_db
      DB_PORT: 5432
      JWT_SECRET: test_secret
      APP_ENV: test
    volumes:
      - .:/app
    command: go test -v -coverprofile=coverage.out ./... 