name: Deploy to Railway

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # Login to Railway
          railway login --browserless $RAILWAY_TOKEN
          
          # Deploy to Railway
          # Railway will automatically inject DATABASE_URL and other environment variables
          railway up --detach 